"""added date ordered field

Revision ID: 0948af6eae2a
Revises: f2fa8ff237c9
Create Date: 2025-01-19 16:36:45.598786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0948af6eae2a'
down_revision = 'f2fa8ff237c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_ordered', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('date_ordered')

    # ### end Alembic commands ###
